_commit: v0.1.0-13-ga6cd339
_src_path: git@github.com:benwebber/open-data-toronto-copier.git
name: DineSafe
project: open-data-toronto-dinesafe
repo: benwebber/open-data-toronto-dinesafe
slug: dinesafe
url: https://open.toronto.ca/dataset/dinesafe/
